apiVersion: v1
kind: Pod
metatada:
  name: result-app-pod
  labels:
    name: result-app-pod
    app: demo-voting-app
spec:
  containers:
    - name: result-app
      image: dockersamples/examplevotingapp_result
      ports:
        - name: result-app-port
          containerPort: 80
